---
- hosts: all

  tasks:

    - name: get uptime
      shell: /usr/bin/uptime
      changed_when: False
      register: uptime

    - name: get uptime
      shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
      changed_when: False
      register: uptime